### ISSUE TITLE
Плагин не получает список групп

### ISSUE THREAD

**Issue by andrvin** [alexanderzobnin/grafana-zabbix#102]
Здравствуйте! Прежде всего хотел бы поблагодарить Вас за работу!
Однако у меня возникла с ним проблема:
при попытке подключиться к Zabbix в логах начинается шквал обращений от grafana к api_jsonrpc.php

В консоли браузера:
TypeError: Cannot read property '0' of undefined
    at ZabbixAPI.p.getGroupByName (http://myserver:3000/public/app/plugins/datasource/zabbix/zabbixAPIWrapper.js?bust=1445608798709:306:16)
    at ZabbixAPI.p.hostFindQuery (http://myserver:3000/public/app/plugins/datasource/zabbix/zabbixAPIWrapper.js?bust=1445608798709:465:19)
    at n.$scope.updateHostList (http://myserver:3000/public/app/plugins/datasource/zabbix/queryCtrl.js?bust=1445608798709:139:35)
    at n.$scope.selectHostGroup (http://myserver:3000/public/app/plugins/datasource/zabbix/queryCtrl.js?bust=1445608798709:56:14)
    at fn (eval at <anonymous> (http://myserver:3000/app/app.bd986dd5.js:13:23184), <anonymous>:4:236)
    at n.$eval (http://myserver:3000/app/app.bd986dd5.js:12:11572)
    at http://myserver:3000/app/app.bd986dd5.js:14:9236
    at http://myserver:3000/app/app.bd986dd5.js:14:15457
    at f (http://myserver:3000/app/app.bd986dd5.js:9:6207)
    at $$writeModelToScope (http://myserver:3000/app/app.bd986dd5.js:14:15416)

в полях 'Group' 'Host' присутствует только один возможный выбор - All
похоже что grafana не может получить список групп - возможно причина в том, что в Zabbix их 46
Прошу если есть такая возможность помочь разобраться, не хотелось бы отказываться от такого удобного инструмента.

**Comment by simple-snow** [comment]
hi
We have over 70 groups on zabbix and don't have problem like you described. Maybe you have specific symbols in group name?

**Comment by alexanderzobnin** [comment]
@andrvin Здравствуйте! Часто такие проблемы связаны с правами доступа - проверьте, есть ли они у пользователя, который настроен в датасорсе. Если вы создали в Zabbix нового пользователя, например, для работы API, то по умолчанию его список доступа пуст и он не может получить никакой информации.

**Comment by andrvin** [comment]
Спасибо за ответ! Разобрался. На zabbix сервере http аутентификация 
вылечил следующими строками в api_jsonrpc.php
header('Access-Control-Allow-Origin: http://myserver:3000');
header('Access-Control-Allow-Headers: origin, content-type, authorization');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    return;
}

**Comment by alexanderzobnin** [comment]
То есть у вас аутентифицикацию пользователей выполняет веб-сервер? Вы настраивали в датасорсе Basic-аутентификацию?

**Comment by andrvin** [comment]
Да разумеется - но не мог законнектится без этих хидеров

**Comment by alexanderzobnin** [comment]
А какая версия Zabbix?

**Comment by andrvin** [comment]
2.2.10

**Comment by alexanderzobnin** [comment]
Да, в ней есть ньюансы с CORS (у меня в документации указано, это немного не тот случай, но, в целом, похоже).
