### ISSUE TITLE
Triggers panel bug with empty application field

### ISSUE THREAD

**Issue by galindro** [alexanderzobnin/grafana-zabbix#121]
@alexanderzobnin I'm testing the triggers pannel and found a little bug: when you select a group, All hosts and an application that belongs only to the hosts from that group and, after that, you change the group to another one that don't have any hosts with that application, the value of application field is nulled and the pannel trows this error:

```js
Message:
			Cannot read property 'applicationid' of null
		
Stack trace:
			TypeError: Cannot read property 'applicationid' of null
    at https://grafana.socialbase.com.br/app/app.00a93492.js:43:16327
    at i (https://grafana.socialbase.com.br/app/app.00a93492.js:12:3869)
    at https://grafana.socialbase.com.br/app/app.00a93492.js:12:4041
    at n.$eval (https://grafana.socialbase.com.br/app/app.00a93492.js:12:11661)
    at n.$digest (https://grafana.socialbase.com.br/app/app.00a93492.js:12:10092)
    at n.$apply (https://grafana.socialbase.com.br/app/app.00a93492.js:12:11928)
    at https://grafana.socialbase.com.br/app/app.00a93492.js:12:19264
    at e (https://grafana.socialbase.com.br/app/app.00a93492.js:10:26558)
    at https://grafana.socialbase.com.br/app/app.00a93492.js:10:27987
```

**Comment by alexanderzobnin** [comment]
@galindro Thanks for report! Need to fix it.

**Comment by galindro** [comment]
Nice @alexanderzobnin . I'll wait for the fix. I'm here to help :)

**Comment by alexanderzobnin** [comment]
Fixed.
