### ISSUE TITLE
Problem creating variables after upgrade

### ISSUE THREAD

**Issue by famassar** [alexanderzobnin/grafana-zabbix#1593]
When I go to create a variable in a dashboard using Zabbix plugin for Grafana i had this error:
**An unexpected error happened
Dettagli
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.**

I change some dashboards, but the prolem is the same.

Zabbix 6.4.0 / Grafana 9.4.3 / Grafana-zabbix connector 4.3.0

**Comment by janet-sullivan** [comment]
I'm seeing the exact same problem, both on an existing install, and a clean one.

Zabbix 6.4.1 / Grafana 9.4.7 / Grafana-zabbix connector 4.3.0

**Comment by elpito** [comment]
Yes, I have exactly the same problem using Zabbix 6.0 LTS and Zabbix 6.4:

```
An unexpected error happened
Details
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at Tr (https://grafana.host/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource/module.js:85:4227)
    at div
    at div
    at l (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:1472:20)
    at im (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:10631:22860)
    at Tt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:154:127638)
    at form
    at Ie (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:6913:4624)
    at Tt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:154:127638)
    at div
    at div
    at div
    at div
    at re (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:125:13314)
    at a (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:475:3184)
    at div
    at div
    at div
    at W (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:4950:2948)
    at Wt (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:6941:737)
    at Tt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:154:127638)
    at ss (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:6960:11767)
    at $t (https://grafana.host/grafana/public/build/DashboardPage.74bb325f53d47878b2e2.js:451:424)
    at DashboardPage
    at Tt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:154:127638)
    at Suspense
    at r (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:1267:169)
    at Ba (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:4623:333)
    at Yt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:158:13496)
    at Yt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:158:15691)
    at main
    at cs (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:4584:2362)
    at Yt (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:158:9783)
    at div
    at c (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:2522:4092)
    at p (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:32:52076)
    at r (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:5357:17554)
    at r (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:1267:169)
    at g (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:1267:720)
    at S (https://grafana.host/grafana/public/build/512.6743f01f38a1921b4ef9.js:154:125332)
    at Oi (https://grafana.host/grafana/public/build/8224.03cd624a29d01d9e0400.js:4636:127)
```

The previously configured dashboard works normal, only the configuration of variables generates the error.

**Comment by alexanderzobnin** [comment]
Duplicates #1590

**Comment by famassar** [comment]
Sorry for the duplice issue...
