### ISSUE TITLE
grafana-zabbix 1.9: Unknown provider:  ZabbixAPIDatasource 

### ISSUE THREAD

**Issue by blacked** [alexanderzobnin/grafana-zabbix#22]
I try to use grafana-zabbix from branch `grafana-1.9` with: grafata 1.9.1, zabbix 2.2.1, and zabbix accessible over self-signed certificate.
After all steps in manual I got black grafana screen and error in browser javascript console:
```
Error: [$injector:unpr] Unknown provider: backendSrvProvider <- backendSrv <- ZabbixAPIDatasource <- datasourceSrv
http://errors.angularjs.org/1.3.0-rc.3/$injector/unpr?p0=backendSrvProvider%20%3C-%20backendSrv%20%3C-%20ZabbixAPIDatasource%20%3C-NaNatasourceSrv
    at http://grafana.local/app/app.fea68443.js:8:6499
    at http://grafana.local/app/app.fea68443.js:8:23535
    at Object.d [as get] (http://grafana.local/app/app.fea68443.js:8:22744)
    at http://grafana.local/app/app.fea68443.js:8:23630
    at d (http://grafana.local/app/app.fea68443.js:8:22744)
    at Object.e [as invoke] (http://grafana.local/app/app.fea68443.js:8:23068)
    at http://grafana.local/app/app.fea68443.js:8:23648
    at Object.d [as get] (http://grafana.local/app/app.fea68443.js:8:22744)
    at d.service.datasourceFactory (http://grafana.local/app/app.fea68443.js:18:11618)
    at null.<anonymous> (http://grafana.local/app/app.fea68443.js:18:10995)
```

**Comment by nucleusv** [comment]
I recommend to use plugin for grafana 2 from develop branch 
'Cause the plugin for grafana 1.9 will not be developed in future as I know

**Comment by alexanderzobnin** [comment]
Very strange. Please, show first 15-20 lines from your datasource.js
 file. Especially this line:
`module.factory('ZabbixAPIDatasource', function($q, $http, templateSrv) {`

**Comment by blacked** [comment]
I make git clone from grafana-1.9 branch, and I didn't modify it:
```define([
  'angular',
  'lodash',
  'kbn',
  './queryCtrl',
],
function (angular, _, kbn) {
  'use strict';

  var module = angular.module('grafana.services');

  module.factory('ZabbixAPIDatasource', function($q, backendSrv, templateSrv) {

    function ZabbixAPIDatasource(datasource) {
      this.name             = datasource.name;
      this.url              = datasource.url;

      // TODO: fix passing username and password from config.html
      this.username         = datasource.meta.username;
      this.password         = datasource.meta.password;

      // For testing
      this.ds = datasource;
    }
```

**Comment by blacked** [comment]
Maybe I put plugin in wrong place?
This is how my grafana directory structure looks like:
```
.
├── app
│   ├── app.fea68443.js
│   ├── app.js
│   ├── components
│   │   └── require.config.js
│   ├── controllers
│   │   └── console-ctrl.js
│   ├── dashboards
│   │   ├── default.json
│   │   ├── empty.json
│   │   ├── scripted_async.js
│   │   ├── scripted_gen_and_save.js
│   │   ├── scripted.js
│   │   ├── scripted_templated.js
│   │   └── template_vars.json
│   ├── features
│   │   └── panellinkeditor
│   │       └── module.html
│   ├── panels
│   │   ├── graph
│   │   │   ├── axisEditor.html
│   │   │   ├── legend.popover.html
│   │   │   ├── module.html
│   │   │   └── styleEditor.html
│   │   ├── singlestat
│   │   │   ├── editor.html
│   │   │   └── module.html
│   │   ├── text
│   │   │   ├── editor.html
│   │   │   └── module.html
│   │   └── timepicker
│   │       ├── custom.html
│   │       ├── editor.html
│   │       ├── module.html
│   │       └── refreshctrl.html
│   └── partials
│       ├── annotations_editor.html
│       ├── confirm_modal.html
│       ├── console.html
│       ├── dashboard.html
│       ├── dashboard_topnav.html
│       ├── dasheditor.html
│       ├── dashLoaderShare.html
│       ├── edit_json.html
│       ├── elasticsearch
│       │   └── annotation_editor.html
│       ├── graphite
│       │   ├── annotation_editor.html
│       │   └── editor.html
│       ├── help_modal.html
│       ├── import.html
│       ├── influxdb
│       │   ├── annotation_editor.html
│       │   └── editor.html
│       ├── inspector.html
│       ├── loadmetrics.html
│       ├── metrics.html
│       ├── modal.html
│       ├── opentsdb
│       │   └── editor.html
│       ├── paneleditor.html
│       ├── panelgeneral.html
│       ├── playlist.html
│       ├── roweditor.html
│       ├── search.html
│       ├── share-panel.html
│       ├── submenu.html
│       ├── templating_editor.html
│       └── unsaved-changes.html
├── build.txt
├── config.js
├── config.js.bak
├── config.js.graphite
├── config.js.influxdb
├── config.js.orig
├── config-replace.js
├── config-replace.js.bak
├── config.sample.js
├── css
│   ├── bootstrap.dark.min.css
│   ├── bootstrap.light.min.css
│   ├── bootstrap-responsive.min.css
│   ├── grafana.dark.min.87051ba1.css
│   ├── grafana.dark.min.css
│   ├── grafana.light.min.8bae5632.css
│   └── grafana.light.min.css
├── font
│   ├── FontAwesome.otf
│   ├── fontawesome-webfont.eot
│   ├── fontawesome-webfont.svg
│   ├── fontawesome-webfont.ttf
│   └── fontawesome-webfont.woff
├── img
│   ├── checkbox.png
│   ├── checkbox_white.png
│   ├── check_radio_sheet.png
│   ├── cubes.png
│   ├── fav16.png
│   ├── fav32.png
│   ├── fav_dark_16.png
│   ├── fav_dark_32.png
│   ├── glyphicons-halflings.png
│   ├── glyphicons-halflings-white.png
│   ├── kibana.png
│   ├── light.png
│   ├── load_big.gif
│   ├── load.gif
│   ├── logo_transparent_200x.png
│   └── small.png
├── index.html
├── LICENSE.md
├── NOTICE.md
├── plugins
│   ├── custom.panel.example
│   │   ├── editor.html
│   │   ├── module.html
│   │   └── module.js
│   ├── datasource
│   │   └── zabbix
│   │       ├── datasource.js
│   │       ├── partials
│   │       │   ├── annotations.editor.html
│   │       │   ├── config.html
│   │       │   └── query.editor.html
│   │       ├── plugin.json
│   │       └── queryCtrl.js
│   └── datasource.example.js
├── README.md
├── test
│   ├── karma.conf.js
│   ├── mocks
│   │   └── dashboard-mock.js
│   ├── specs
│   │   ├── dashboardSrv-specs.js
│   │   ├── dashboardViewStateSrv-specs.js
│   │   ├── gfunc-specs.js
│   │   ├── graph-ctrl-specs.js
│   │   ├── graphiteDatasource-specs.js
│   │   ├── graphiteTargetCtrl-specs.js
│   │   ├── graph-specs.js
│   │   ├── graph-tooltip-specs.js
│   │   ├── helpers.js
│   │   ├── influxdb-datasource-specs.js
│   │   ├── influxQueryBuilder-specs.js
│   │   ├── influxSeries-specs.js
│   │   ├── kbn-format-specs.js
│   │   ├── lexer-specs.js
│   │   ├── parser-specs.js
│   │   ├── row-ctrl-specs.js
│   │   ├── seriesOverridesCtrl-specs.js
│   │   ├── sharePanelCtrl-specs.js
│   │   ├── templateSrv-specs.js
│   │   ├── templateValuesSrv-specs.js
│   │   ├── timeSeries-specs.js
│   │   └── timeSrv-specs.js
│   ├── test-main.js
│   └── tests.html
└── vendor
    ├── angular
    │   └── angular-mocks.js
    ├── css
    │   ├── animate.min.css
    │   ├── font-awesome.min.css
    │   ├── normalize.min.css
    │   ├── spectrum.css
    │   └── timepicker.css
    ├── jquery
    │   ├── jquery.flot.fillbetween.js
    │   └── jquery.flot.pie.js
    ├── license.json
    └── require
        ├── css-build.js
        ├── require.js
        └── tmpl.js

32 directories, 142 files
```

**Comment by alexanderzobnin** [comment]
Looks like you use `master` branch. This code from it.

**Comment by blacked** [comment]
Oops. You are right. Thanks!

**Comment by alexanderzobnin** [comment]
Use release 1.0.1 instead clone repo to prevent mistakes.
https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v1.0.1

**Comment by alexanderzobnin** [comment]
Do you have any reasons to use grafana 1.9.1 instead 2.0? There are many new usefull features in this release and in grafana-zabbix for grafana 2 (templates? multiple graphs from one target and more).
