### ISSUE TITLE
Error to create panels

### ISSUE THREAD

**Issue by robertofgama** [alexanderzobnin/grafana-zabbix#337]
Message: Cannot read property 'filter' of undefined

Stack trace:
TypeError: Cannot read property 'filter' of undefined
    at eval (http://10.0.0.2:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484831827312:563:70)
    at Array.forEach (native)
    at ZabbixAPIDatasource.replaceTargetVariables (http://10.0.0.2:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484831827312:562:19)
    at eval (http://10.0.0.2:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484831827312:234:21)
    at l (http://10.0.0.2:3000/public/app/boot.b8fccc44.js:52:14654)
    at Function.Sg [as map] (http://10.0.0.2:3000/public/app/boot.b8fccc44.js:53:15348)
    at ZabbixAPIDatasource.query (http://10.0.0.2:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484831827312:231:30)
    at b.issueQueries (http://10.0.0.2:3000/public/app/boot.b8fccc44.js:46:4632)
    at b.issueQueries (http://10.0.0.2:3000/public/app/boot.b8fccc44.js:19:2788)
    at g (http://10.0.0.2:3000/public/app/boot.b8fccc44.js:42:13902)

**Comment by alexanderzobnin** [comment]
@robertofgama can you describe in details what exactly you do?

**Comment by robertofgama** [comment]
I make my instalation  and the process of integration with Zabbix and all occurred normaly, but when i will make the graphics exist a exclamation uppon the graphic then the message is this

**Comment by 20100507** [comment]
I also encountered the same problem.
`Cannot read property 'filter' of undefined`
```
TypeError: Cannot read property 'filter' of undefined
    at eval (http://192.168.146.129:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:563:71)
    at Array.forEach (<anonymous>)
    at ZabbixAPIDatasource.replaceTargetVariables (http://192.168.146.129:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:562:19)
    at eval (http://192.168.146.129:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:234:21)
    at m (http://192.168.146.129:3000/public/build/vendor.2c3c591224fb193f7fd3.js:1:53401)
    at Function.ps [as map] (http://192.168.146.129:3000/public/build/vendor.2c3c591224fb193f7fd3.js:1:94558)
    at ZabbixAPIDatasource.query (http://192.168.146.129:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:231:30)
    at e.issueQueries (http://192.168.146.129:3000/public/build/0.62c2e3e7aa607c7f2d09.js:7:17800)
    at e.issueQueries (http://192.168.146.129:3000/public/build/0.62c2e3e7aa607c7f2d09.js:7:204121)
    at u (http://192.168.146.129:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69119)
```
