### ISSUE TITLE
Zabbix API error 

### ISSUE THREAD

**Issue by roysbike** [alexanderzobnin/grafana-zabbix#392]
Grafana 4.2
zabbix 3.2.5

Message
Cannot read property 'forEach' of undefined

TypeError: Cannot read property 'forEach' of undefined
    at expandItems (https://zabbix3.fabit.ru/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixAPI.service.js?bust=1493970211902:172:18)
    at i (https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:42:21962)
    at https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:42:22384
    at o.$eval (https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:42:29539)
    at o.$digest (https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:42:28012)
    at o.$apply (https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:42:29822)
    at https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:43:5172
    at f (https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:41:8103)
    at https://zabbix3.fabit.ru/public/app/boot.5ee7468a.js:41:9564

Проблема странная, на вид все ок . Часть графиков грузится, а часть нет.

**Comment by roysbike** [comment]
Разобрался. Коннекты к БД закончились
