### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by julianoromani** [alexanderzobnin/grafana-zabbix#514]
### I'm submitting a ...
- [X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.3   | 3.0.13  | 3.8.1                 |

#### What did you do?
Add a table panel to get windows log items from zabbix.

#### What was the expected result?
Show windows log captured by zabbix.

#### What happened instead?
For some windows show log, for anothers I receive this error.

Zabbix API Error
{"error":"Internal Server Error","response":"","message":"Internal Server Error"}

On table show
Cannot read property 'name' of undefined
And stacktace is
TypeError: Cannot read property 'name' of undefined
    at eval (http://smo.actec.rs/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/responseHandler.js:46:24)
    at http://smo.actec.rs/grafana/public/build/vendor.2305a8e1d478628b1297.js:1:71240
    at http://smo.actec.rs/grafana/public/build/vendor.2305a8e1d478628b1297.js:1:78058
    at fr (http://smo.actec.rs/grafana/public/build/vendor.2305a8e1d478628b1297.js:1:68501)
    at http://smo.actec.rs/grafana/public/build/vendor.2305a8e1d478628b1297.js:1:77863
    at Nr (http://smo.actec.rs/grafana/public/build/vendor.2305a8e1d478628b1297.js:1:71212)
    at Function.pa [as map] (http://smo.actec.rs/grafana/public/build/vendor.2305a8e1d478628b1297.js:1:93893)
    at convertHistory (http://smo.actec.rs/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/responseHandler.js:44:14)
    at Object.handleText (http://smo.actec.rs/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/responseHandler.js:74:12)
    at eval (http://smo.actec.rs/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:505:42)

**Comment by alexanderzobnin** [comment]
This is an error on the server side. Try to check PHP logs.
