### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by unclebob2013** [alexanderzobnin/grafana-zabbix#57]
TypeError: Cannot read property '0' of undefined
    at ZabbixAPI.module.factory.p.getGroupByName (http://192.168.131.128:3000/public/app/plugins/datasource/zabbix/zabbixAPIWrapper.js?bust=1437288629438:306:16)
    at ZabbixAPI.module.factory.p.hostFindQuery (http://192.168.131.128:3000/public/app/plugins/datasource/zabbix/zabbixAPIWrapper.js?bust=1437288629438:465:19)
    at l.module.controller.$scope.updateHostList (http://192.168.131.128:3000/public/app/plugins/datasource/zabbix/queryCtrl.js?bust=1437288629438:139:35)
    at l.module.controller.$scope.init (http://192.168.131.128:3000/public/app/plugins/datasource/zabbix/queryCtrl.js?bust=1437288629438:25:14)
    at ge.functionCall (http://192.168.131.128:3000/app/app.6e379bdb.js:13:14399)
    at l.$get.l.$eval (http://192.168.131.128:3000/app/app.6e379bdb.js:12:5068)
    at tc.compile.pre (http://192.168.131.128:3000/app/app.6e379bdb.js:13:29246)
    at fa (http://192.168.131.128:3000/app/app.6e379bdb.js:10:7723)
    at v (http://192.168.131.128:3000/app/app.6e379bdb.js:10:1625)
    at h (http://192.168.131.128:3000/app/app.6e379bdb.js:9:29738) <div ng-repeat="target in panel.targets" class="tight-form-container ng-scope" ng-class="{'tight-form-disabled': target.hide}" ng-controller="ZabbixAPIQueryCtrl" ng-init="init()">

what`s wrong?

**Comment by alexanderzobnin** [comment]
Try to use code from [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch.

**Comment by alexanderzobnin** [comment]
@unclebob2013 Is it helpful?

**Comment by unclebob2013** [comment]
thanks ，it works！

**Comment by incoquinita** [comment]
Hi Alexander,

Recently I updated my Grafana to 4.6.3 and the Zabbix plugin to 3.8.1 and I started to face this problem again when I use a templating and a host don't have the selected item (as we can see in attached photo)


![image](https://user-images.githubusercontent.com/29259509/35858073-53d81b24-0b22-11e8-84d2-1fd0d1e57499.png)

**Comment by alexanderzobnin** [comment]
It seems it's outdated a little bit.
