### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by b1nary1** [alexanderzobnin/grafana-zabbix#571]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.0   | 3.4.8  | 3.9.1                 |

#### What did you do?
I select such a range, when data is retrieved from trends instead of history and check the value for Singlestats with Options -> Stat set to "Current"

#### What was the expected result?
It should display "N/A" (it was so previously - "N/A" is my value map to "null")

#### What happened instead?
It shows "N/A", however, JS Error "Cannot read property 'name' of null" is displayed along.

![1](https://user-images.githubusercontent.com/34511754/39811345-074c3b16-5391-11e8-811d-fc428a358118.png)
![2](https://user-images.githubusercontent.com/34511754/39811233-b9b1409a-5390-11e8-8c54-a41efa292c55.png)

**Comment by xiaoxue999** [comment]
same to me..
TypeError: Cannot read property 'name' of null
    at eval (http://10.128.240.200:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:169:27)
    at m (http://10.128.240.200:3000/public/build/vendor.0cea50118711e7e6c839.js:1:53401)
    at Function.ps [as map] (http://10.128.240.200:3000/public/build/vendor.0cea50118711e7e6c839.js:1:94558)
    at convertGrafanaTSResponse (http://10.128.240.200:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:168:27)
    at ZabbixDBConnector.handleGrafanaTSResponse (http://10.128.240.200:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:128:18)
    at eval (http://10.128.240.200:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:407:52)

**Comment by champriven** [comment]
also same to me！！

please fix bug quickly

TypeError: Cannot read property 'name' of null
    at eval (http://10.6.30.70:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:169:27)
    at h (http://10.6.30.70:3000/public/build/vendor.950b64c220f766b8b5f3.js:1:53965)
    at Function.ls [as map] (http://10.6.30.70:3000/public/build/vendor.950b64c220f766b8b5f3.js:1:95237)
    at convertGrafanaTSResponse (http://10.6.30.70:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:168:27)
    at ZabbixDBConnector.handleGrafanaTSResponse (http://10.6.30.70:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:128:18)
    at eval (http://10.6.30.70:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:407:52)

**Comment by tornado67** [comment]
Grafana 5.2, Zabbix 3.4.11 , same

TypeError: Cannot read property 'name' of null
    at eval (http://<ip>:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:169:27)
    at h (http://<ip>:3000/public/build/vendor.950b64c220f766b8b5f3.js:1:53965)
    at Function.ls [as map] (http://<ip>:3000/public/build/vendor.950b64c220f766b8b5f3.js:1:95237)
    at convertGrafanaTSResponse (http://<ip>10.124.0.222:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:168:27)
    at ZabbixDBConnector.handleGrafanaTSResponse (http://<ip>:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:128:18)
    at eval (http://<ip>:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:407:52)
    at <anonymous>

**Comment by akshaygupta2208** [comment]
I am also facing the same issue
Cannot read property 'name' of null
 I can see this as closed but no one mentioned any solution or workaround.
