### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ManthysBR** [alexanderzobnin/grafana-zabbix#660]
**Describe the bug**

Grafana shows the message "Cannot read property 'name' of undefined" when bringing data to a dashboard. When i refresh the page it goes away to another item from the same dashboard and it randomizes.

TypeError: Cannot read property 'name' of undefined
    at eval (http://10.16.16.15:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/responseHandler.js:46:24)
    at http://10.16.16.15:3000/public/build/vendor.dfabdd44b3be44288eac.js:9:21550
    at http://10.16.16.15:3000/public/build/vendor.dfabdd44b3be44288eac.js:9:27964
    at Vr (http://10.16.16.15:3000/public/build/vendor.dfabdd44b3be44288eac.js:9:17818)
    at http://10.16.16.15:3000/public/build/vendor.dfabdd44b3be44288eac.js:9:27769
    at di (http://10.16.16.15:3000/public/build/vendor.dfabdd44b3be44288eac.js:9:21522)
    at Function.Ka [as map] (http://10.16.16.15:3000/public/build/vendor.dfabdd44b3be44288eac.js:9:40622)
    at convertHistory (http://10.16.16.15:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/responseHandler.js:44:14)
    at Object.handleHistory (http://10.16.16.15:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/responseHandler.js:62:12)
    at eval (http://10.16.16.15:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:411:42)

**Expected behavior**
It should bring just the data into the dashboard.

**Screenshots**

https://i.imgur.com/d7Y8QCT.png

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix  | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.4.2  | 4.0.3  | 3.9.1

<img width="892" alt="erroapi" src="https://user-images.githubusercontent.com/40351156/50708637-2cff5280-104c-11e9-9532-ed69d52b65a6.png">
                 |

**Comment by Phil57** [comment]
This has been fixed in https://github.com/alexanderzobnin/grafana-zabbix/issues/571 but not released yet.
@alexanderzobnin Any idea on a ETA ? Our graphs started randomly not loading.

**Comment by xiaoxue999** [comment]
Fixed with 3.10 ,try the new version..

**Comment by Phil57** [comment]
> Fixed with 3.10 ,try the new version..

Just updated, confirm it's working fine now. Thanks
