### ISSUE TITLE
"Cannot read property 'name' of null" for "Total cpu

### ISSUE THREAD

**Issue by vainkop** [alexanderzobnin/grafana-zabbix#667]
Grafana:
`v5.4.3 (6539180)`
Zabbix:
`4.0.3`
Zabbix Template:
`https://share.zabbix.com/operating-systems/windows/windows-grafana-template`

Message:
`Cannot read property 'name' of null`
Stack trace:
```
TypeError: Cannot read property 'name' of null
    at eval (http://zabbix.example.com:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:169:27)
    at Qt (http://zabbix.example.com:3000/public/build/vendor.469095018b321ef1da7c.js:9:5767)
    at Function.Ka [as map] (http://zabbix.example.com:3000/public/build/vendor.469095018b321ef1da7c.js:9:40622)
    at convertGrafanaTSResponse (http://zabbix.example.com:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:168:27)
    at ZabbixDBConnector.handleGrafanaTSResponse (http://zabbix.example.com:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/zabbixDBConnector.js:128:18)
    at eval (http://zabbix.example.com:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:407:52)
```
![grafana-zabbix-01](https://user-images.githubusercontent.com/28118190/51737416-9697dd00-209d-11e9-8a16-10edd3f7e15a.jpg)

**Comment by vainkop** [comment]
The issue resolved after a while, I guess some network issue.
